# Generated by Django 5.0.2 on 2024-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='card_holder_name',
            field=models.CharField(default='No Name Provided', max_length=100),
        ),
    ]
