# Generated by Django 5.0.2 on 2024-03-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
            ],
        ),
    ]
