# Generated by Django 5.0.2 on 2024-03-24 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_cityselection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTickets',
            fields=[
                ('theater', models.CharField(max_length=255)),
                ('movie', models.CharField(max_length=255)),
                ('showtime', models.DateTimeField()),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
