# Generated by Django 5.0.2 on 2024-03-24 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_movietickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietickets',
            name='tickets',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
