# Generated by Django 5.0.2 on 2024-03-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_movietickets_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietickets',
            name='showtime',
            field=models.CharField(max_length=25),
        ),
    ]
