# Generated by Django 5.0.2 on 2024-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_movietickets_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietickets',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
