# Generated by Django 5.0.2 on 2024-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_movietickets_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='card_holder_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
