# Generated by Django 5.0.2 on 2024-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_cityselection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='line1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='line2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phno',
            field=models.IntegerField(default=0),
        ),
    ]
