# Generated by Django 5.0.2 on 2024-03-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userprofile_country_userprofile_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
