# Generated by Django 5.0.2 on 2024-03-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userprofile_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='expiry_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='expiry_year',
            field=models.IntegerField(null=True),
        ),
    ]
