# Generated by Django 5.0.2 on 2024-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_paymentdetail_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityselection',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
