# Generated by Django 5.0.4 on 2024-04-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_otpstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportLOCID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
