# Generated by Django 5.0.4 on 2024-04-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_flightbooking_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='user',
            field=models.CharField(default='123', max_length=20),
        ),
    ]
