# Generated by Django 5.0.4 on 2024-04-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_flightbooking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='123', max_length=20)),
                ('booking_id', models.CharField(max_length=100, unique=True)),
                ('hotel_name', models.CharField(max_length=100, unique=True)),
                ('business_id', models.CharField(max_length=100, unique=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('price', models.FloatField()),
                ('payment_card_ending', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='HotelCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dl_number', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='user.hotelbooking')),
            ],
        ),
    ]
