# Generated by Django 5.0.4 on 2024-04-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_hotelbooking_hotelcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='business_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
    ]
