# Generated by Django 5.0.4 on 2024-04-20 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_hotelbooking_business_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrauntBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='123', max_length=20)),
                ('booking_id', models.CharField(max_length=100, unique=True)),
                ('restraunt_name', models.CharField(max_length=100)),
                ('business_id', models.CharField(max_length=100)),
                ('visit_date', models.DateField()),
                ('payment_card_ending', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RestrauntCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dl_number', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='user.restrauntbooking')),
            ],
        ),
    ]
